package.json

In the settings view, this extension's options show up under the misleading heading "Example configuration." This corrects that issue; the new heading is "Haskell Language Server."

Corrected title in configuration

---

package.json
src/commands/constants.ts
src/commands/showType.ts
src/extension.ts

Added `Show type` command. 
This command returns and displays type of the "current" expression. The expression gets highlighted, and if `Show command` is called again, then it widens the scope and then shows the type of a "bigger" expression.
Default binding is set to be `Cmd+Opt+t`.
Some of it can potentially be moved to `haskell-ide-engine`, but having a feature seems useful.

Added Show Type command

---

package-lock.json
package.json
src/docsBrowser.ts
src/extension.ts

`HIE` provides very useful links to documentation and source in a hover popup. Unfortunately, `VSCode` now opens these links in its tabs as HTML source, not as readable documentation.
The issue was tracked in https://github.com/Microsoft/vscode/issues/36452 with the resolution that this behaviour is expected.
This PR fixes the issue by opening haddock docs and sources in a human-readable form:

Show docs as docs, not as sources

---

src/extension.ts

Seems I wasn't the only one annoyed with the output window constantly getting focus, as per https://github.com/angular/vscode-ng-language-service/issues/128, https://github.com/Microsoft/vscode/issues/36844 and many more.
According to https://github.com/emberwatch/vscode-ember/issues/2 it seems setting `revealOutputChannelOn: RevealOutputChannelOn.never` will stop the output window from taking over focus.

Stop the output window from taking focus

---

Changelog.md
Contributing.md
README.md

Updated the README a bit to look better on the VS Code marketplace. Also added a Contributing.md taking over  the generic `vsc-extension-quickstart.md`, and move changelog information out into a separate file.

Polish the README and other documentation

---

package.json

Sets the banner color to a dark purple, ala what we use on Haskell.org, and the theme to dark. This is merely a suggestion, but thought it'd make it would give it a bit more lively look :)

Set marketplace banner colors and theme

---

.gitignore
.travis.yml
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
.vscodeignore
package.json
tsconfig.json

A few last manual steps are needed for the `.travis.yml` file to be done.
1) Insert an encrypted GitHub OAuth API key with `travis setup releases`
2) Enable Travis for alanz/vscode-hie-server
3) Go to the travis page for the project at, https://travis-ci.org/alanz/vscode-hie-server
a) Under `More Options` go into `Settings`
b) Set a environment variable `VS_TOKEN` with the value of your VS Code personal token
c) Make sure `Display value in build log` is turned OFF!
A couple of options for 1., either just comment with the output of the encrypted key here, or somehow allow my user to make releases? Or, we can just forego the process entirely and just keep it on the marketplace itself. 
2) should be straight forward :)
Let me know if there's something missing. Also, while I know we aren't …

Set up travis initial deployment script and testing

---

src/extension.ts

Closes https://github.com/alanz/vscode-hie-server/issues/34 :Win32 uses `where`

Fix HIE installation check on Win32 Platforms

---

hie-wrapper.sh
package.json
src/extension.ts

Following up on https://github.com/haskell/haskell-ide-engine/issues/439.
This adds a hie-wrapper.sh script, which tries to automatically select a hie version that matches the GHC version of the project.
It is enabled by a configuration flag, `useHieWrapper`, which is set to false by default, until we know if it is stable enough to enable by default. It assumes that the user has built different versions of hie and postfixing them with the GHC their are built for (falling back to plain `hie`). I've added a Makefile to make this easy in https://github.com/haskell/haskell-ide-engine/pull/447.
I'm amenable to any changes to the script etc, just let me know if there's something you would prefer instead!
Also, I set `debug=1` for now, so one can `tail -f /tmp/hie-wrapper.log` to see if it …

Add configuration to use hie-wrapper to launch hie (default: false)

---

package.json
src/extension.ts

Allow a user to specify the full path to a custom hie wrapper script. The intended use case for this is to allow the user themselves to support workflows that might not be officially supported yet, or simply is necessary because of a differing configuration than the standard.
This would e.g. provide support for nix users to setup their own wrapper script, to get HIE working, as requested in https://github.com/alanz/vscode-hie-server/issues/48.
The PR intentionally does not support `“use hie.sh in a dominating directory”` though, because this can be achieved with a workspace setting in VSCode.

Allow the path to a custom hie wrapper to be specified in settings, fixes #48

---

src/commands/insertType.ts

The current `insertType` seems to be broken.
I revert this to the old version.
When I executed InsertType, I got the following error.
Because haskell-lsp got `workspace/executeCommand` with empty params.
```
error log:
[Error - 11:07:30] haskell-lsp:parse error. Object (fromList [("jsonrpc",String "2.0"),("params",Object (fromList [])),("method",String "workspace/executeCommand"),("id",Number 21.0)]) "When parsing the record ExecuteCommandParams of type Language.Haskell.LSP.TH.DataTypesJSON.ExecuteCommandParams the key command was not present." `stack update` and install new haskell-lsp. Or check information on https://marketplace.visualstudio.com/items?itemName=xxxxxxxxxxxxxxx
```
https://github.com/haskell/haskell-ide-engine/issues/468

Fixed `insertType` command

---

README.md
src/extension.ts

Cleaning up some mistakes in my earlier PR #49 , this PR adds support for the user to be able to substitute `${HOME}`/`${home}`/`~` with the home folder and `${workspaceFolder}`/`${workspaceRoot}` with the project/workspace folder.
Furthermore, since a custom wrapper wouldn't correctly work with a direct `which hie` command, the `isInstalledCheck` is skipped when `useCustomWrapper` is enabled.
Finally, Windows support is added, by adding `!useCustomWrapper` to the windows check for `startupScript`, so it won't switch to the .bat file if `useCustomWrapper` is enabled.
Sorry for the inconvenience in the earlier PR being slightly broken, I've tested this one, and it works. I used the following `custom-wrapper.sh` in both my project folder and home folder,
```bash
export …
```

Hie custom wrapper support for path variable substitution and Windows

---

Changelog.md
README.md
package-lock.json
package.json
src/commands/insertType.ts
src/commands/showType.ts
src/extension.ts

Preliminary support for multi-root workspaces. The idea is to launch a HIE server for each folder in the workspace, since they could vary in GHC versions etc.
Additionally, this also sets the scopes on various configs to be either window (global/workspace configurable) or resource (folder in multi-root workspace configurable), e.g. supporting custom hie wrappers and some options per folder basis in the multi-root workspace.
My ultimate goal with this is to provide some nicer support for working in a shared code setup with backend, common, frontend (currently testing with [this Miso setup](https://github.com/Tehnix/miso-isomorphic-stack)).
There are some kinks here and there. If you want to help test it, you can set up a workspace in VS Code by either
- right click in the file tree/sidebar …

[WIP] Set up HIE to support multi-root workspaces

---

package-lock.json
package.json
src/docsBrowser.ts

- Fix `Documentation` link for newer VSCode
**Note:** As @halhenke suggested, we should be looking for https://code.visualstudio.com/updates/v1_21#_webview-api for the future versions of this functionality

Fix documentation under newer VSCode lang server

---

.vscode/settings.json
package-lock.json
package.json

Includes new code action support

Update vscode-languageclient to v4.2.0

---

hie-vscode.bat
hie-vscode.sh
hie-wrapper-old.sh
hie-wrapper.sh

Instead of trying to choose the right version in our own wrapper.
This needs to be updated/checked for windows and mac.
Help please.

Use the exe hie-wrapper from haskell-ide-engine

---

package.json
src/extension.ts

This PR accompanies haskell/haskell-ide-engine#530.
Example:
```haskell
f :: Either Int String -> [Char]
f e = "Hello World"
```
put your cursor in front of the `e` identifier and run `Haskell: Split case`.
The result should be:
```haskell
f :: Either Int String -> [Char]
f (Left e) = "Hello World"
f (Right e) = "Hello World"
```
It works as long as the cursor is on the identifier that you wish to generate pattern matches for.
Let me know what you think!

Add command for case splitting

---

src/commands/importIdentifier.ts

`moduleLine` is now the first line (once trimmed) that is `"where"` or ends with `" where"` or ends with `")where"`.
In respect of testing, I've tried the modified command and it seems to work as expected.

Fix #98 Import identifier insertion line

---

README.md

I've updated the readme to reflect the [currently recommended](https://github.com/haskell/haskell-ide-engine#installation-with-stack) way of installing hie.

Update installation instructions to match haskell-ide-engine instructions 

---

Changelog.md
package-lock.json
package.json

Requires vscode 1.25, provides hierarchical document symbol support

Update vscode-languageclient to 4.4.0

---

hie-vscode.sh

- I was getting the error "mismatch GHC version, maybe use hie-wrapper" in VSCode
- I checked `ps aux | grep hie` and saw that `hie` was launched by `hie-vscode.sh` (instead of `hie-wrapper`)
- Updating the bash script with this fix, I relaunched VSCode and `ps aux | grep hie` showed that `hie-vscode.sh` had now launched `hie-wrapper` and `hie-8.2.2`
- Note: I'm not sure if the windows `.bat` script is also broken?

Fix hie-vscode script to use hie-wrapper if available

---

hie-vscode.bat

Bugfix for: https://github.com/alanz/vscode-hie-server/issues/135
Clears the `__COMPAT_LAYER` variable before running the wrapper so that the ```stack ghc -- --numeric-version``` command doesn't fail and cause fallback behavior. 
Original thread for access violations: https://github.com/commercialhaskell/stack/issues/3765

Bugfix for stack version on Windows

---

src/docsBrowser.ts

I remember being able to search the documentation/source window before vscode deprecated previewHtml. This commit is to bring back that functionality.

Enable find widget for doc/source view

---

hie-vscode.sh

It's been gone for a while now

Remove unused lsp flag

---

hie-vscode.sh

If `hie-wrapper` bombed, the script would run on down to invoke `hie` a second time

Fix hie being run if hie-wrapper crashes

---

package.json

Adds the option to package.yaml so that it shows up in VSCode's
settings.
Fixes #39

Expose diagnosticsOnChange option

---

README.md

The default install method takes a lot of time with a good chance of it being the sort of install that you don't want.

warn about compile time and wrapped hie

---

src/extension.ts

In accordance with [Make casesplit a HaRe action](https://github.com/haskell/haskell-ide-engine/pull/917).

Update casesplit plugin.

---

README.md

Recommend `./install.hs build` instead of the now removed `./install.hs build-all`.
Add section on installing on Windows.
Closes #175

Update HIE install instructions

---

Changelog.md
package.json
src/extension.ts

If this flag is set to true, we will not add the `--lsp` flag when
launching hie/hie-wrapper.
Should alleviate #186, #185, #187

Introduce noLspParam flag to config

---

package.json

Hi! This should complement https://github.com/haskell/haskell-ide-engine/pull/1481. Is there anything else to be done for the VSCode extension to recognise and operate with the formatter on HIE?

Added ormolu as a formatting provider

---

package.json
src/commands/constants.ts
src/commands/restartHie.ts
src/extension.ts

Add restart command.

---

README.md

Closes #199
I've added instructions to install it with cabal too.
/cc @flip111

Update hie build instructions

---

default.nix

After generating yarn.lock, simply run `nix-build` to create a
derivation containg the webpacked plugin, package.json and the
hie-vscode wrappers.

Add Nix expression to build and run webpack

---

README.md

* I've removed the multi-root workspace cause it used the removed hie-wrapper setting: we could restore it using other example
* I think use cases of hie-wrapper could be covered with the hie executable path, in case any user depended on it

Adapt README to the new extension settings

---

src/extension.ts

But if there is a folder, still keep track of it in the list of running
clients

Allow the server to be launched on standalone .hs files

---

package.json

In `package.json`, some commands aren't updated accordingly to the recent command name change, resulting in #243 
This pull request just fixes those errors and revives `Restart Server` and `Import identifier` features.
Fixes #243.

Corrects old command names in `package.json` (fixes #243)

---

.travis.yml
Contributing.md
README.md
default.nix
package-lock.json
package.json
src/utils.ts

And finish moving from alanz/vscode-hie-server to haskell/vscode-haskell

Rename vscode-hie-server to haskell

---

src/utils.ts

I ran into "Manual executable missing" when trying to use an absolute `serverExecutablePath` on windows with:
```
"haskell.serverExecutablePath": "C:/path/to/hie_wrapper.exe", // "C:\\path\\to\\hie_wrapper.exe" didn't work either
```
I think the problem stems from the `where` command on windows not having the expected behavior when passed an absolute path:
```
C:\>where c:/Windows/System32/notepad.exe
ERROR: Invalid pattern is specified in "path:pattern".
C:\>where c:\Windows\System32\notepad.exe
ERROR: Invalid pattern is specified in "path:pattern".
```
The commit should solve this but it doesn't check for executable permissions so I was considering something like this:
```typescript
function absoluteExecutableExistsWindows(exe: string): boolean {
try {
fs.accessSync(exe, …
```

Fix absolute paths not working on windows

---

package.json

Since brittany isn't included in the static binaries due to licensing
restrictions
Fixes https://github.com/haskell/vscode-haskell/issues/255

Switch the default formatter to ormolu

---

README.md

Hey!
I noticed that the table for the haskell language server Path location on each platform was rendered incorrectly in the visual studio marketplace. It shows as:
> This extension will download haskell-language-server binaries to a specific location depending on your system. If you find yourself running out of disk space, you can try deleting old versions of language servers in this directory. The extension will redownload them, no strings attached. | Platform | Path | |----------|------| | macOS | ~/Library/Application\ Support/Code/User/globalStorage/haskell.haskell/ | | Windows | %APPDATA%\Code\User\globalStorage\haskell.haskell | | Linux | $HOME/.config/Code/User/globalStorage/haskell.haskell |
I suspect the the extra new line before the table will fix this given that I have had …

Fix the haskell-language-server path table in README.md

---

README.md
package.json
src/extension.ts

It doesn't seem to be needed anymore now that VS Code provides ways of
disabling extensions on a per-workspace basis natively
Closes #268

Remove the haskell.enable configuration option

---

default.nix
package-lock.json
package.json

the vscode package is deprecated: https://www.npmjs.com/package/vscode
Tested by building with nix (after running 'yarn import')

vscode dependency -> @types/vscode

---

package.json
src/hlsBinaries.ts
src/utils.ts
src/validation.ts
tsconfig.json

Use already downloaded tools when fetching latest release metadata fails. This adds a small cache file in the `globalStoragePath` containing the last fetched information.
Does not currently implement the feature as requested in #281 as I'm not certain what exactly such a flag should do (pick one):
- Not download anything at all
- `"haskell.hlsUpdateBehavior": "keep-up-to-date"` Try to fetch latest release information, if that fails fall back to local cache (what is done with this PR automatically)
- `"haskell.hlsUpdateBehavior": "prompt"` Try to fetch latest release information, but not upgrade, even if it succeeds and instead display a prompt to update (probably sensible), still download artifacts for the proper ghc version, if necessary.
- `"haskell.hlsUpdateBehavior": "never-check"` …

Use local files on connection failure, closes #298

---

src/docsBrowser.ts
src/extension.ts

As suggested in abandoned PR #295 , tried to translate local file to the Hackage URL as it's more reliable and doesn't need extra dependencies.
Click to open in browser and close the original tab.  Tested only on Windows but Mac or Linux should work too.
Also can provide option to open on hackage straight away bypassing the VS code tab, although not confident if translation works in 100% of cases.
**Examples:**
**GHC libraries doc**
* Local: file:///C:/Users/KolA/AppData/Local/Programs/stack/x86_64-windows/ghc-8.6.5/doc/html/libraries/base-4.12.0.0/GHC-Maybe.html#t:Maybe
* Hackage: https://hackage.haskell.org/package/base-4.12.0.0/docs/GHC-Maybe.html#t:Maybe
**GHC libraries src doc**
* N/A
**stackage snapshot doc:**
* Local: file:///C:/sr/snapshots/b84f27c3/doc/haskell-lsp-types-0.22.0.0/L …

add "Reopen on Hackage (beta)" hyperlink to doc window

---

README.md

* They were outdated, as noted in #344 
* Soon we will have to add 8.10.4 (and remove 8.10.1)

Update supported ghc versions

---

README.md

With a link to the last release of haskell-language-server

Update ghc supported versions

---

README.md
package.json
src/extension.ts

* I've added some features with demos i had at hand

Make hls the unique language server variant

---

package.json

* Someone could execute a program in the client machine setting the option in the .vscode folder

Set executable path scope to machine

---

Changelog.md
package.json

* Closes #378 
//cc @berberman @isovector

Prepare 1.3.0 release

---

Changelog.md
README.md
package.json

* See #387
* It will suppose a new release (1.4.0)
//cc @marcin-rzeznicki @anka-213 @nc6

Revert serverExecutablePath from machine to resource scope

---

Changelog.md
README.md
package-lock.json
src/hlsBinaries.ts

* Fixes #412 
//cc @runeksvendsen

Prepare 0.15: fix get project ghc version progress and warning about ghc-9

---

package.json

//cc @isovector as this adds two config options for tactics

Update config to last hls schema

---

src/extension.ts

Allows tracking of cabal files so the [cabal-fmt plugin](https://github.com/haskell/haskell-language-server/pull/2047) on hls can access cabal files in order to format them.

Add tracking of cabal files

---

.github/workflows/build.yml

* with the aim of replace travis-ci.org (see https://github.com/haskell/vscode-haskell/issues/385#issuecomment-888024893 for the motivation)
* using https://github.com/marketplace/actions/publish-vs-code-extension
* it publishes on releases created and upload the vsix published to the release asset
* @jaspervdj gently has created the needed secrets in the repo to make the gha work

Release and publish extension using github actions

---

Changelog.md
package-lock.json
package.json
src/commands/constants.ts
src/extension.ts
src/hlsBinaries.ts
src/utils.ts

- Add much more logging in the client side, configured with `haskell.trace.client`
- Fix error handling of `working out project ghc` (See #421)
- And dont use a shell to spawn the subprocess in non windows systems
- Add commands `Start Haskell LSP server` and `Stop Haskell LSP server`
- Hopefully fixes #421

Fix `getProjectGhcVersion` error handling

---

package-lock.json
package.json
src/docsBrowser.ts
src/extension.ts

Tested on my machine, this could fix https://github.com/haskell/haskell-language-server/issues/2068.

Update vscode-languageclient to 7.0.0

---

Changelog.md
package-lock.json
package.json

Prepare 1.6.0

---

package.json
src/docsBrowser.ts
src/extension.ts

It is not a perfect solution but I think it's a bit better than having an empty webview
I removed the iframe and instead pass the html directly to the webview.
I had to set `base` url to the documentation directory so that the css files can be fetched properly. 
The links in the opened documentation are broken and they can't be opened in the webview (at least I couldn't figure out how to do that), when you click on a link it opens it it the users browser but because we have base url set, the opened link points to something like `https://file+.vscode-resource.vscode-webview.net/nix/store/n104dcsv7gc8l7c2mc2lixp220il8lk8-ghc-8.10.4-doc/share/doc/ghc/html/libraries/base-4.14.1.0/Control-Monad.html#t:Monad`.
An alternative is to have the css files required for correct haddocks rendering in …

Fix showDocumentation command.

---

package.json
src/extension.ts

Add an option to set server command line arguments

---

package-lock.json
package.json

* Include the bump of `webpack`, as advised by dependant-bot alert and `npm audit`
* `haskell.plugin.refineImports.globalOn` is not listed in `haskell-language-server generate-default-config`
* i've not added `haskell.checkParents` as i am not sure if it is sensible to expose it to final users (//cc @pepeiborra)

Add config options from last hls version

---

Changelog.md
README.md
package.json

//cc @cdsmith and @pranaysashank as this will include your recent work here, many thanks to both!

Prepare 1.7.0

---

src/extension.ts

Closes #468
It seems that `vscode-languageclient` will concatenate the arguments array into a string that our server won't accept if there are blank strings in the array.

Make sure no empty strings in server executable args

---

src/extension.ts

* To help diagnose issues related with them, specially with $PATH (like https://github.com/haskell/haskell-language-server/issues/2314)

Trace environment variables

---

.github/workflows/build.yml
.github/workflows/test.yml
package.json
src/extension.ts
src/utils.ts
test/runTest.ts
test/suite/extension.test.ts

* A recent github workflows vm update set ghc to 9.2.1 in Linux, and hls does not support it
* This pr uses haskell/actions/setup to explicitly set a supported ghc version (9.0.1)
* In the way i added some improvements to help to debug the issue:
* The client log output is written in the log file is the config option is specified
* Client log output has a more verbose level: debug
* Tests use the log file contents to make checks, it is included in the workflow step and uploaded as artifact if the test suite fails
/cc @jacobprudhomme, as i have modified some of the code recently added in your pr

Fix ci: ensure we have a supported ghc version in PATH

---

.github/workflows/test.yml
src/hlsBinaries.ts
src/utils.ts

Here's a simplistic PR for addressing #454. Probably too simplistic but maybe something to start with (I've never done any TypeScript before, and JavaScript last time in 1998 lol). 
This PR cannot cope with prior versions of `latestApprovedRelease.cache.json`, so make sure to start with a clean local cache (on Linux at `:~/.config/Code/User/globalStorage/haskell.haskell`.

support old hls versions compatible with the requested ghc version

---

src/hlsBinaries.ts

Add more traces and suggestions for users
I find a corner case where the behaviour is not ideal: if you have downloaded the old release metadada *for 1.5.0* and then you have set `haskell.updateBehaviour` to `never-check`, the unique release info in the new release metadata is 1.5.0 and it will fail to use a possibly existing hls-1.4.0-8.10.4 (as the info for such binary is in the release metadata for 1.4.0)
It is fixed setting again  `haskell.updateBehaviour` to `up-to-date` so i've suggested use that to try to find a binary in "other releases" (newer or older)
//cc @mduerig

Add traces for download hls

---

package.json

Related issue: https://github.com/haskell/vscode-haskell/issues/502

Fix hole_severity option: Use integer instead of string

---

src/hlsBinaries.ts

The Haskell Platform install link for Windows is [deprecated](https://www.haskell.org/platform/index.html#windows). Windows users can use [GHCup](https://www.haskell.org/ghcup/) to install as well.

fix: change deprecated Haskell Platform install link to GHCup

---

README.md

Just a quick update of the README, which still listed HLS 1.5.1 and no support for GHC 9.2.1.

Update README.MD GHC support

---

README.md
package.json
src/commands/importIdentifier.ts
src/extension.ts
src/hlsBinaries.ts
src/utils.ts
test/suite/extension.test.ts

Consider user installed HLSes (e.g. via ghcup compile)

---

package.json

Eval plugin gains new configuration options in haskell/haskell-language-server#2622 (diff) and haskell/haskell-language-server#2775 (exception).

Add eval plugin configuration

---

.github/workflows/test.yml
README.md
package.json
src/extension.ts
src/hlsBinaries.ts
src/utils.ts
test/suite/extension.test.ts

This will most likely fail in CI, because of https://gitlab.haskell.org/haskell/ghcup-hs/-/commit/0c70feb09c54bf06ee9ceddfaf808b2ca1027688

Manage all the Haskell things

---

src/hlsBinaries.ts

The user doesn't need to see the full output, if they truly need it,
they can consult the extensions output and otherwise the user may be
overloaded with output.
Turns this:
Into this:

Remove stdout/sterr from user error message

---

README.md
package.json
src/extension.ts
src/hlsBinaries.ts
test/suite/extension.test.ts

Wrt https://github.com/haskell/vscode-haskell/issues/561
----
Example config in current workspace:
```json
{
"haskell.toolchain": {
"hls": "1.6.1.1",
"cabal": "recommended",
"stack": null
}    
}
```
This means:
1. install the `ghc` version corresponding to the project (default, because it's omitted)
2. install hls 1.6.1.1
3. install the recommended cabal version from ghcup
4. don't install any stack version
Another config:
```json
{
"haskell.toolchain": {
"ghc": "9.2.2",
"hls": "latest"
"cabal": "recommended",
}    
}
```
1. install ghc 9.2.2 regardless of what the project requires
2. always install latest HLS, even if it doesn't support the given GHC version
3. install recommended cabal
4. install latest stack (default, because it's omitted)

Introduce 'haskell.toolchain' setting

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/test.yml
.prettierignore
README.md
package.json
src/commands/importIdentifier.ts
src/extension.ts
src/hlsBinaries.ts
test/runTest.ts
test/suite/extension.test.ts
yarn.lock

Add prettier script

---

package.json

We can't perform pre-releases otherwise.

Bump required VSCode version

---

.github/workflows/release.yml

According to https://github.com/HaaLeo/publish-vscode-extension/issues/16#issuecomment-1095419698 pre-releases to VSX Marketplace already work, docs are just outdated.
So, enable it to have automatic pre-releases to VSX Marketplace on Pre-release tagging in Github

Enable pre-release feature for VSX Marketplace

---

Changelog.md
Contributing.md
package.json

Additionally, add a release checklist for future contributors.
Most notably, this version is changed to `2.1.0` to follow the version recommendation at https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions
> ... we recommend that extensions use major.EVEN_NUMBER.patch for release versions and major.ODD_NUMBER.patch for pre-release versions. For example: 0.2.* for release and 0.3.* for pre-release.
with the reasoning:
> VS Code will auto update extensions to the highest version available, so even if a user opted into a pre-release version and there is an extension release with a higher version, that user will be updated to the released version.
So, the next  *proper* release is going to be `2.0.1`, and the next pre-release is `2.1.0`. Unless …

Prepare pre-release 2.1.0

---

src/extension.ts

Avoids leaking secrets in Env Vars and makes it safe to paste logs.

List Env Vars we care about only

---

src/errors.ts
src/extension.ts
src/hlsBinaries.ts

Introduces HlsError hierarchy because there might be more errors in the future (Apparently, I can't shake off my java developer education)
Also, removes ad-hoc defined `[boolean, string, string]` type because no one can remember the meaning of such a construct. Replaces with class and proper name.

Add Tool class and print stacktraces

---

GenChangelogs.hs

This way the list can be copy-pasted into ChangeLog.md and fits the style of the rest of the document

Add indentation for list item in markdown

---

src/extension.ts
src/hlsBinaries.ts
src/utils.ts

Add various logging statements.
Demote excessive logging to debug level.
Refactor hard to read functions.
Add more typing information.

Ignore missing entries in Release Metadata

---

src/errors.ts
src/extension.ts

Improve error message, fixes #587

---

src/hlsBinaries.ts

Fix confusing download dialog popup

---

src/hlsBinaries.ts

Architecture type now:
```haskell
type Architecture = 'arm' | 'arm64' | 'ia32' | 'mips' | 'mipsel' | 'ppc' | 'ppc64' | 's390' | 's390x' | 'x64';
``` 
Hope that's the correct type.

Replace x32 with ia32 for Architecture matching

---

package.json
src/extension.ts

The trace server option is useful for debugging the JSON messages sent between the LSP client and server. A standardized output format is provided by `vscode-languageclient/node`, compatible with this [lsp inspector tool](https://github.com/microsoft/language-server-protocol-inspector).
To get the LanguageClient to read the trace server option from the config, the `id` passed to the language client needs to match the section used in `getConfiguration`. I also add a verbose option to the config, since it is supported by the LanguageClient.

Fix trace.server option

---

.github/dependabot.yml
.github/workflows/test.yml
README.md
src/extension.ts
src/hlsBinaries.ts
test/suite/extension.test.ts

The test-suite has its fair-share of issues and tests some things it is
not supposed to test. We remove tests that do not test functionality
that comes from vscode-haskell.
Overhaul CI to use only ghcup instead 'haskell/action/setup'

Fix test-suite for new GHCUp release

---

README.md

Shouldn't a problem report contain sensible information? 😉

Change sensible to sensitive

---

README.md

Add link to HLS installation webpage

---

Changelog.md
GenChangelogs.hs
README.md
package.json

Publish configuration changes #736 and fix #529
This is a conservative release before we upgrade some major versions of the dependencies.
Also, potentially last release before #618 is merged.

Prepare release 2.2.2

---

src/errors.ts

Hey!
I've noticed one of the documentation links wasn't working properly, this PR fixes it.

Update unsupported GHC doc link

---

Changelog.md
README.md
package.json
yarn.lock

Breaking changes make the latest version unusable with current versions of HLS.
Together with a release, this should fix #852

Downgrade vscode language client to 7.0.0

---

.github/workflows/test.yml
test/suite/extension.test.ts

Still not sure how it is so slow, but make CI green at least.

Fix broken tests

---

package.json
src/utils.ts
yarn.lock

This code became obsolete after #896

Remove unused code

---

.github/workflows/test.yml
test/suite/extension.test.ts

This pr includes:
1. Remove some `Promise` and turn to simple sleep with a timeout to check if the target file exists, making it easy for maintainers(at least myself) to evaluate the test's effect.
2. Make ghcup in CI select the version of HLS correctly, it is used to run all tests on ghc-9.6.
3. Remove the CI step `Upload test artifacts` because we have printed the hls.log.
4. Keep the ghc version to be test synced with HLS's.
5. If the user runs the test locally, all temporary products(`test-workspace` dir and `out` dir) will be left. The origin test suite only does clean for `/test-workspace/bin`, it's not enough though, ignore this weakness for future improvement.

Simplify tests

---

package.json
yarn.lock

It causes troubles due to following the newer LSP spec which HLS is not ready for. For details, see https://github.com/haskell/vscode-haskell/issues/920 and https://github.com/haskell/lsp/issues/510, etc...

Downgrade vscode-languageclient

---

.vscode/settings.json
Changelog.md
GenChangelogs.hs
package.json

Also updated `GenChangelogs.hs` to filter dependabot

Prepare release 2.4.1

---

Changelog.md
docs/Release.md
package.json

We are excited to announce the pre-release of a new feature that will greatly enhance the experience with HLS! With this release, we have added comprehensive support for `.cabal` files at the IDE level. This includes advanced features such as file formatting, diagnostics, and auto completions.
One of our talented developers, @VeryMilkyJoe, has worked tirelessly on implementing this feature throughout the summer. We are grateful for this hard work and dedication. Now, we are thrilled to share this exciting update with all of you.
To ensure seamless integration, it is important to note that this functionality requires HLS version **1.8.0.0 or higher**. Failure to meet this requirement may result in `.cabal` files being treated as Haskell files. We are aware that there are currently some …

Prepare pre-release 2.5.0

---

docs/Release.md

Document the knowledge gainde from #941

Update release docs for refreshing CI tokens

---

test/suite/extension.test.ts
test/suite/index.ts

Hope this can relieve https://github.com/haskell/vscode-haskell/issues/928...

Increse time limitation to make test on Windows more stable

---

.github/workflows/test.yml

Following https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html, HLS has dropped ghc-8.10.7 after hls-2.2.0.0, so we can replace 8.10.4 with 8.10.7 and hope it can make our test more stable...

Bump old hls version and upgrade test runner to macos-latest

---

src/extension.ts

It seems this fixes the issue of #1010. It is currently completely a mystery to me why we didn't set this option before, and what the real issue is. Why does it seem only reproducible on MacOS.

Always set the cwd for the executable

---

README.md

Address invalid byte sequence error

---

docs/Release.md

Add release branch policy

---

Changelog.md
package.json
src/extension.ts

In accordance to our new branching policy, we are merging the pre-release back into master. The branch `release-2.4` has been created containing all changes up to f54fee6d6a70ea5f0174ffad49c4bda441895e49

Merge Pre release 2.5 into master

---

package.json

Companion to https://github.com/haskell/haskell-language-server/pull/3860. Shouldn't be merged until that is.
The added lines come from manually inspecting the output of `cabal run exe:haskell-language-server vscode-extension-schema`. Do we have a better automatic process for this (I'm sure it'd be fairly easy to script with `jq`, perhaps after an initial commit re-ordering things)?

Add `haskell.plugin.fourmolu.config.path` option

---

package.json

See https://github.com/haskell/haskell-language-server/issues/4178 for details.

Add Session Loading style to list of known configs

---

.github/workflows/package.yml
.github/workflows/test.yml

Split out packaging action

---

.eslintrc.json
.github/workflows/package.yml
.github/workflows/release.yml
.github/workflows/test.yml
.vscode/extensions.json
Changelog.md
GenChangelogs.hs
package.json
src/errors.ts
src/hlsBinaries.ts
src/utils.ts
yarn.lock

Contains all commits from master except #618

Prepare 2.4.4

---

package.json
yarn.lock

from 7.0.0 so that can register inlay hints provider.
link https://github.com/haskell/haskell-language-server/pull/4235.

bump vscode-languageclient version to 9.0.1

---

package.json
src/extension.ts
src/hlsBinaries.ts

Support for `.cabal` files was implemented in HLS 2.0.0.0. But the vscode-haskell extension does not enable this Language Server support, because it would break for older HLS binaries, as these were unable to handle file updates for `.cabal` files.
To work-around, we had a pre-release of the vscode-haskell plugin, which enabled support for `.cabal` plugins in an opt-in fashion.
It's been a while, and we want to enable language server support for `.cabal` files unconditionally. There are still HLS binaries around that can't handle `.cabal` files, but it much less.
For the unfortunate souls left behind with GHC versions such as 8.6.5, we add a new vscode-haskell option:
haskell.supportCabalFiles
This option is `true` by default, but if set to `false` it will unconditionally **disable** …

Add option to enable/disable `.cabal` file support

---

.vscode/launch.json

Webpack output is in `dist` dir., but launch.json was pointing to wrong location.
This change makes vscode aware of sourcemap location, and fixes breakpoints in debugger

Make js debugger work
