- hie-vscode.sh
- package.json
- src/commands/constants.ts
- src/commands/insertType.ts
- src/extension.ts
- Insert type for top-level and inlined expressions
**Note** This PR is implemented against the `cleanup` branch of the `ide-engine`
> Implement insert type command

- hie-vscode.bat
- src/extension.ts
Added a batch script analog to hie-vscode.sh, and a couple conditionals to detect platform at runtime.
> Added .bat file for startup on Windows

- README.md
Also while I was at it, minor re-wording of first paragraphs for more conciseness.
> Added link to extension on marketplace

- package.json
@alanz totally forgot about this and just saw your comment!
> Add extension dependency for syntax highlighting

- src/extension.ts
> Check for hie exe on activate and display error message if not found.

- package.json
Honoured in hie using https://github.com/alanz/haskell-ide-engine/tree/settings
Addresses https://github.com/haskell/haskell-ide-engine/issues/320
> Add setting to turn off hlint.

- src/extension.ts
Last PR broke for me - not sure if its a dependency thing but if not this is what fixed things.
> Import `RevealOutputChannelOn`

- .vscode/settings.json
- package-lock.json
- package.json
- src/commands/constants.ts
- src/commands/insertType.ts
- src/commands/showType.ts
- src/docsBrowser.ts
- src/extension.ts
- tslint.json
Referring to #29 
Not sure if these particular set of rules are what people want. If theres anything you want added/removed let me know.
[](https://palantir.github.io/tslint/rules/)
> Added basic tslint support

- package-lock.json
- package.json
- src/commands/insertType.ts
- src/commands/showType.ts
- src/docsBrowser.ts
- src/extension.ts
Mainly this is an update to `tslint` configuration and fixes for some of the remaining issues that were found as a result of that. Basically some rules need type related information to properly lint and so you have to pass the `tsconfig.json` file as an argument to `tslint`:
https://palantir.github.io/tslint/usage/type-checking/ 
After doing this a bunch of unused variable errors popped up. Also updated a few dependencies and made a small change to the `docsBrowser` to reflect a change in API.
> Tslint update

- .prettierrc
- .vscode/settings.json
- .vscode/tasks.json
- Contributing.md
- README.md
- package-lock.json
- package.json
- src/commands/insertType.ts
- src/commands/showType.ts
- src/docsBrowser.ts
- src/extension.ts
- test/extension.test.ts
- test/index.ts
- tsconfig.json
- tslint.json
This PR adds automatic code formatting, using prettier, and adds a commit hook via husky, that formats code. It also adds stronger TypeScript configurations and linter requirements, which helps make the code more robust.
I'm personally a very big proponent on automatic formatting, especially in multi author/writer projects like this, but I want to hear if anyone has anything against this. The goal is to streamline the code across contributors, who usually each have their own style.
> Prettify/reformat all code, add stronger TS config and lint requirements

- README.md
Update installation instructions for HIE to be again in sync with newest update in HIE. 
See HIE issue **[https://github.com/haskell/haskell-ide-engine/issues/534]()** and HIE pull request **[https://github.com/haskell/haskell-ide-engine/pull/535]()**
> Update README.md (installation of HIE)

- src/extension.ts
> Use os.tmpdir()

- hie-wrapper.sh
- package-lock.json
- package.json
To avoid a security vulnerability
> Update wrapper to detect GHC 8.4, update package lock file

- package-lock.json
- package.json
- src/commands/constants.ts
- src/commands/importIdentifier.ts
- src/extension.ts
This command adds the chosen import to the top of the file (if it doesn't exist), and adds the package to the list of dependencies in the hpack `package.yaml` (if it doesn't exist).
> Add an Import identifier command

- src/extension.ts
> Fix multiple hie processes issue

- package-lock.json
- package.json
To complement https://github.com/haskell/haskell-ide-engine/pull/810
> Add snippet config option

- package-lock.json
- package.json
And update package-lock.json to fix a vunerability npm found
Complements https://github.com/haskell/haskell-ide-engine/pull/1080
> Add formatterProvider config

- src/docsBrowser.ts
Fixes #141 by moving from the deprecated previewHtml command to the new Webview API when viewing Haskell documentation. See [vscode issue #62630](https://github.com/Microsoft/vscode/issues/62630) on the deprecating previewHtml timeline. It appears they will remove vscode.previewHtml entirely from the product in a few weeks' time.
> Show documentation content using Webview API

- .travis.yml
- Changelog.md
- package-lock.json
- package.json
Via vscode-languageclient version 6.0.0.next.3
> Bump protocol version to 3.15 prerelease

- Changelog.md
- package.json
But the vsix does not seem to work.
> Preparing for Version 0.0.30

- Changelog.md
- package-lock.json
- package.json
Mainly for security advisories, update to vscode-languageclient-6.1.3
> Bump dependencies

- package.json
- src/hlsBinaries.ts
- src/utils.ts
> Mirror support

- README.md
- package.json
* Related pr in hls: https://github.com/haskell/haskell-language-server/pull/1567
> Remove max number of problems config option

- package.json
> Correct wingman config options types

- .travis.yml
* Not sure what i am doing 😄 
* I've removed the release to github, as it seems it never was used
* Closes  #250
> Deploy to open.vsx

- package-lock.json
- package.json
* Checking the list of `haskell-language-server --vscode-extension-schema` (thanks @berberman!) using the released version
* Progress towards #378
//cc @berberman @isovector
> Add rest of hls-1.1.0 config options

- package.json
> Fix tactics config

- Changelog.md
- package.json
* Urgent pr to fix #471 
//cc @berberman
> Prepare 1.7.1

- package.json
- src/extension.ts
Add option to ignore haskell-language-server on PATH
relate to #461 #500
> Add ignorePATH option

- package-lock.json
- yarn.lock
Generated by `npm audit fix`. I place all my trust in this tool, if something's broken, blame `npm`.
> Fix npm security issue

- .github/workflows/test.yml
This line was accidentally added by me
> Remove accidental run command

- .github/workflows/build.yml
> Upgrade VSCode publishing github action version

- .github/workflows/release.yml
> Simplify release script

- docs/Contributing.md
- docs/Release.md
Split Contributing and Release for better orientation.
Add one more item for the release-checklist.
> Add docs folder

- Changelog.md
- package.json
- yarn.lock
Followed the release-checklist, performing minor version dependency upgrade
> Prepare release 2.0.1

- src/hlsBinaries.ts
If you're new to HLS you won't necessarily know what to choose,
and the dialog should help you in this case.
At Zurihac, @fendor and I helped SPJ get VS Code running with HLS, and after being shown this popup he mentioned he would really appreciate an indication of which option to choose if you have no idea what to choose.
> Toolchain management dialog: add hint for beginners

- package.json
See https://github.com/haskell/haskell-language-server/pull/3284.
> Add Fourmolu config property

- .github/workflows/release.yml
- .github/workflows/test.yml
> Fix release CI

- README.md
See https://code.visualstudio.com/api/references/extension-manifest#approved-badges
> Update badge url for VSCode Marketplace

- package.json
I saw #909  failed because of this.
PS: The last newline was removed by format on save.
> Bump vscode to 1.80.0

- package.json
- src/extension.ts
> Add tracking of cabal files

- package.json
This PR will follow with a prompt release due to https://github.com/haskell/haskell-language-server/issues/3885
> Add stan plugin option
